[theme]
# Primary accent color for interactive elements.
primaryColor = "#123473"

# Background color for the main content area.
backgroundColor = "#123473"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#f5c658"

# Color used for almost all text.
textColor = "#fff"
#textColor = "#273133"