[theme]
# Primary accent color for interactive elements.
primaryColor = "#0e4d4d"

# Background color for the main content area.
backgroundColor = "#123473"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#135e53"

# Color used for almost all text.
textColor = "#fff"
#textColor = "#273133"

